apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: todde
data:
  config.yaml: |
    tunnel: bc12cc01-ac86-41fd-8df2-2d12ff734ef6
    credentials-file: /etc/cloudflared/credentials/credentials.json

    ingress:
      - hostname: api.toddemanos.com
        service: http://ingress-nginx-controller.todde.svc.cluster.local:80
      - hostname: toddemanos.com
        service: http://ingress-nginx-controller.todde.svc.cluster.local:80
      - hostname: argocd.toddemanos.com
        service: http://ingress-nginx-controller.todde.svc.cluster.local:80
      - hostname: grafana.toddemanos.com
        service: http://ingress-nginx-controller.todde.svc.cluster.local:80
      - service: http_status:404
