apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: todde
data:
  config.yaml: |
    tunnel: bc12cc01-ac86-41fd-8df2-2d12ff734ef6

    ingress:
      - hostname: api.toddemanos.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: toddemanos.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: argocd.toddemanos.com
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404
