apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: todde
type: Opaque
stringData:
  token: eyJhIjoiMTNiY2ZiODA1MjJiZmVmMTVlZDE2MjQ1NGMxMmExNDUiLCJzIjoiWkRVNE5EQmhPV1F0TkRWaFppMDBOMk5pTFRsa01ETXRaakl6TWpZME4ySXdaRGMyIiwidCI6ImJjMTJjYzAxLWFjODYtNDFmZC04ZGYyLTJkMTJmZjczNGVmNiJ9