apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: todde
type: Opaque
stringData:
  credentials.json: |
    REPLACE_ME  # JSON-filen du laddar ner från Cloudflare när du skapar tunneln