---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-redis-credentials
  namespace: todde
spec:
  encryptedData:
    password: AgAvR0zsT9joOswrIANf2iWl7nh38ukSTO5vQCP4srhHvIp1lbDAK/cw3pjSvW8g7owIg/0yq5fVkSUiBwEX9/sk1QeYlUTjJM1Pz7xzvJe5PvAUvXeILeB/lwH35IzMcU7ZFex2ZsUI4Ij9yjfMDfE5SVSfbgT65Ee0EtLLo5KUaQtUQZtcIleI+J2Q/5R415q2Q36wyJMoZPWGck8fVWCJey6IIhfVZC0X2dt8mcEr65titcSqdaOI2MlVySUa5xd1N/F5Q+ItdfsmMV2Pc7mny6J0+3pZLyh8ynVJ0NJ/WgXfmiU1JosNRKA8//KJV1Y7y1aK72u0Jq+LZwSOJCac7IZ6RFvrKLzM7YjkfNGe/Ej+f1bRstqEFjF+1s/CFOqyiaaoQc8TjbA1O4bQw6+BhCUwfnsUgBMf41ji3pGjnd8A5ewh73jlhdGfsATQxvfdd9zDNPTu2XhauTTuP3LwaElrLTaQ7VWeG3iHSU9RBNzdxwk+AHexBrVBuYNxktYHBKFG+tzw2REKHBSObXLjwsjSfEllU5pNGGlhT0IbPaquapSO2g+FCKIlRePOY1sb5Nvt8wywBRsWO8xnlCAgQ0Dzk8CBXInpiU6x71V9R/AQSGU3wdGe0EN8Ih60H02M2Z1VShnM2Pqv4XZguEG0QF4DYDL6iymvilbqgCmXzV7I3JRNGtQMz8ZkmorXSfctDA68wPkZpQqa31EtP5+LvH3cIGgehXOirXxtHSiAAA==
  template:
    metadata:
      creationTimestamp: null
      name: forge-redis-credentials
      namespace: todde
    type: Opaque
