apiVersion: v1
kind: ServiceAccount
metadata:
  name: forge-api
  namespace: todde
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forge-ingestor
  namespace: todde
---
# forge-api får bara läsa secrets — inte skriva
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forge-api-role
  namespace: todde
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forge-api-rolebinding
  namespace: todde
subjects:
  - kind: ServiceAccount
    name: forge-api
    namespace: todde
roleRef:
  kind: Role
  apiGroupd: rbac.authorization.k8s.io
  name: forge-api-role