apiVersion: v1
kind: Secret
metadata:
  name: forge-mongodb-credentials
  namespace: todde
type: Opaque
stringData:
  mongodb-root-password: REPLACE_ME      # byt ut
  mongodb-replica-set-key: REPLACE_ME    # byt ut — intern auth mellan replica-noder, kan vara ett långt random-värde