---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-mongodb-credentials
  namespace: todde
spec:
  encryptedData:
    mongodb-replica-set-key: AgB4jMnSt5dBc5wGgqhjLAz0YvARWJYxfPLaqm4+S9zJYDN578pCta8BhmGTiOspT7ftJQtpmiCpZ7AeXK7dFRBt2Y/QN5Bhcr+aqst4jn7Vi9Cnf/WKegyCS43KAs8ZAnW/5YXtLGV2ah5/ZpK/gdVLVg0mtBy/WLlFNX597iGpDWwOvM8/jCpTQxHjQnmIJZcpTBYrQJNFzC7uigb1ZDGv5uw4lhMwEedQ61Gj9gLqcWTE37F5jiW4KX4pjMQj6kqSXOqDAaYIH24v9DeuQAAqUfuwyk2Z9k2LeWz4AG0Mi12cpivbo2XdpmNwZsUn+pT3FrsCun/bcFyvt9QBbNNQCBcAlkhBuWWWaxWONDdV77Cj0y7eA+4jidjkpc1DyXZbOebSW6W+gjjxxJh+Vn6TXP6P3GhAft62oyHdMyAfCkeLmPj4FhTZN89S0LtK7LVVZeTnAce06W7bnOkGHxeLD7zA2Ljkud1El+NWN+AD5jO5XWZilV5NV3Kk/5CJGJsol4nmSqu5VwtDpPrH2gD+4KKbN9vPdS7Lk4Y0tKPIpOB8gtxC+6imoLkEqSqvrQseqIAEAae/9uduQ8Xm3Hw9IB1QbRd6HKcAt+4860d/GC+tBypKGGqlzbiL3I5MDBM6NyJ5dRbOMf3KiUCQrA9DIbX1xM6+PnldXZiRGyjL4FUfmXlsQgsHwRZzmmJcBKa0nrxfRrH1HWDTdQpzrZQIAHCrhuaPhKRM7GF/UTQW/g==
    mongodb-root-password: AgCT7G11PYPtW6QaD6MUQ/k2Sqnj/jUKQe9wVWMehf9w+4EwBz9wBiUu00Ji9P62mmTOzeSH34gdEucNaKkFqyush/Akb1aTG+A/27iBM1nUwcyvxYLc5JPrW/gTUuzwtFGkY5eMDtHn1XxdZCHs5UimIwDXk2nmf77Bw1htColNp7FGN57KobCMqEQmDWmfwiMJJNAIrirZzyNSZiBqbWmSXAHztNpR5s0Rsh7gIqvJEEGf7BPeNEn2iEwFrkP/gKzgQzzT1ABprABBhu1g5unFZdJB4XXVr30vzokfpUW2nop33w5oO8iuxSYq7lcm34kvHclu5HFpoqyWYfLaQbs1bg0nOgd5Cqx5ifMXRJtGGyUg1wVAHJvM/QmCCScIJv6VJkiF9kzOtqkQ8g23f8ZVdExGYSpilVZorRo0hPoFI0UnHA2m6RRCs4SHNVx94dSjS7/zbdwx8Y9jINAX3y5admywsUbJZ0102x+/g3L+aUNA7EtJxMdTdgDvln2IZgyJvblnxgRKTA26N1OVNTJerLo8jOB9c1wOKUVZ+QnWbNaVs7dHLrDP4eKS2g41xHRjN7Z9XH6gb8GNpFZkCK31ANOTOG03buNrPP/YukjugkOnEz28yn769RRZcUtqQu1tOV7VWlztzDITuKtrUYNUksZui+5rriiu1eGMMkCFgspbJSotVqf6oM4FhpYEX/37m0ndmgH8floPq9qY6rdt+5PPTHkNZ6QzLHBrObUFDg==
  template:
    metadata:
      creationTimestamp: null
      name: forge-mongodb-credentials
      namespace: todde
    type: Opaque
