apiVersion: v1
kind: Secret
metadata:
  name: forge-ingestor-secrets
  namespace: todde
type: Opaque
stringData:
  github-token: REPLACE_ME
  github-username: REPLACE_ME
  mongodb-uri: REPLACE_ME   # mongodb://forge:PASSWORD@forge-mongodb.todde.svc.cluster.local:27017/forge_events