---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-timescale-credentials
  namespace: todde
spec:
  encryptedData:
    password: AgAW4WQRbdy6HKcmBZpVB+h5mT91QODEtyTfrnlQuJTVsCCEAdtGjpbHe5lc5r4pKc2yCyQtvHms0y+MT6crktHolL7TvwZ03jhtH1WrFAgqQFH/VbGUunTcLxm8ti2Ju9tK/4YlfMj5cOIe1KHhKNid/K8849LhZY8PaUwEUNRef56rAV3iv1SWw6iNoyC037an9hKiGw75MZ10Qdn9iJAbiBTqcCMsnfgIp0GqtK/PBWIm2Fe50vwFTvmeh46OHbRPETD7KgRle3fiFFDf4Je3cWrwH905trmZwz6UW5J1zjMZcB/Y4QOmVHWAg07a+S2MIJ9yAyscFJbYAC3tiENsMlkg0LwHIOvSHHjOrf0Nw8QHD5lYsojoVZyytpBEX6nnFVoj/d7ne3H/loKCuhslWx2k58nNB5uG85v2MoyDKMV6GSb3B20Pi02dBoh7tRwif0l2JZImSfidytEiEmsXVfnO6dhjDAV7cxWBm2XxYTCKj97ni98OUyCgFdwuVkjvfYZXGw/uLx3XsG3u7NEhrkvVY49T9Ydkvxo/BAAUorQGuv8+8wgSoiojXRsZJ1ljPTQTSlc7459AhdWeppFqds/G9uM1urubr81eP1H039nQFYoz5N28ZDFiymlgDg3shiks0u6ym3qkPzSxSqJP+uu2uQcce/RgY+lbcOVu6yKO4Qyq1RxZ04GFLrxtpBNR/v2hMzLMoYq9Eb0xxy/mUXPrzJvyny/GKX4Hjct4QA==
    username: AgClGD1cg4tgU3mLk46Cq6Uemy6/j8wqmu8tsA1hHPjvkV7jjhfZVFfMukOzF4tMyk+x8EtHQapk1kn/fnHF9F0wMUv7Wqg29NoLjw0TLtz+to8ixd6k+brEXDu6yC+wbnD8poY73LIjuxdVemGf7Nck0M2ICXPL9EDEJ5tV5KXunv+yKRQJpdK9W/aMd3tbDxmDZjPoO2EFnBtQ64qODIfEQXEGUIBo3EzV8U+50sn3U9uaNPQ/xqiYw52C3E13vt4AGoq0lhJLrTs7mPwAmCOShrmt4rmRsXkK+p7qGuCyVlRqfKxDE8T+epAKd3MRSZeMbxhVNgpzid+6DpCmN9/U23JwZENN44aH+3QM9MqWfQCSHNuNrzWKdgJwI1/XwhVsf9pNiXy22Xxqzrk+5cJvU4qqgrXJoxeS9HxgValE4GGZCRQOoxXqpfgdd1QIkMZFTzW7ynQ/txBrB+QD7lQMU6cw7FFTXXUBQMwkZxQUckdBRC3CY8eYn7vvHRPunRdH2Ifk1JDcd5hn3uCMeyqsujk6UFYVn5n8f+xP2dk88HQSn/z2f0sPkR211FClhXsusVcU1lL4X90pcRpg1DddK3Wiar0LdAr9lzqIEwr//xGEKOVicyrIy3W8tuW+wLrKip8j94J4q2B6aGDndSwbrPEPtmzLHYQOa0/ynJPewN9uVR9TgWRBQtku6PCGjPu6ALJEej0t5rfvE7Yh
  template:
    metadata:
      creationTimestamp: null
      name: forge-timescale-credentials
      namespace: todde
    type: kubernetes.io/basic-auth
