---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-elasticsearch-credentials
  namespace: todde
spec:
  encryptedData:
    password: AgAlSbd7MX5ux2CCIR4Sa5sHZQcj6hNaSWfWrwAqUbo2SkoEZv1NP9r9lnnqQ8OwDIY7P7xjO923uSFzzlv6EwVAH8nLHkdsj9u7oazr70mqGEznc1RCK7FsClRHEj56h17srI3xtw/ab14AagEUa3CdiiZAQeG/1zwEsw9B3tdJKHXDyVKvW/ZZFS8CLV8rdJoWJ93Tmc/f01yfoVaAixSDxgYufaMqqJB9SM2nHiqD9uKPb7c2ddeAD+wafCwYzf/z2PkDvrasZkwv08NgwH/B26PiawUDQydufNTKONFAa5X1A2IEJQqbE56gZlTFSs6UOKBJ2Tmj+h9qoI+OUZEGFGkeNWsG6ULOLw091wg1DOyNbYkUyx9M9YA5C+IwPzmunwe1vpbpaMg1D+mhOle7tmLvGvHNmS3pYwGfl8hhu5DX6e7fXVnzTuqrY/3hwusYzl/rydRABY35VyvhwKGuOYBQLTN8iGmsbwJXn0CNcJFO/AzPNS7LElqinIiuzbqA8/uRF1RQXKQGq0gJ+7rWk0qy0qtvs6IQio+/sICqrmCNK0ZAyLTqXA4NcVjn9N2wEERQONOOLS9EBYzM8Xu5Voxely509RFu407k3+4aHevt7lihhd0Tj0oA0TWEQSbgmLdbEep1pXCO2Ub8s9yEmHW7mztAIJFT8U94Fo5C1hfxPz2Ya8i2JfAsEs8VYIxUwqyq09kK3bruIPIqzceNrJ3nLBZYkFVeSiYIn6BIdQ==
  template:
    metadata:
      creationTimestamp: null
      name: forge-elasticsearch-credentials
      namespace: todde
    type: Opaque
