---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-api-secrets
  namespace: todde
spec:
  encryptedData:
    mongodb-uri: AgAMfRT9idCqddvHm4cLz/qFh7Nd7dPeHnp2CG6wmDWk4thdijI2R7mhL59j20Vgig3+FGYWWDGao/PQ3VoeTWjbBw2KXCASykmO2tSvnwsqHFJxuYbs6M9WaPeeSki0PT9WweNSNU3YxEwR4mac/vsAJYl/rOS9w3YpKhE1OnbZMsJgCKwM8qApvWsqsi2H1R4EUqSWIlZP1DEWq9/0YzbuN4sw7MpXOMzIjcT8cV1PAuEQhSLxJeMX85JuNpw09SoKPmyGZ6Vjc6jQgL3vZ639936BdBF8kQz/vM/PskvHP8aqdxF4vwecio0oiUvUf73S6AAcWZ7aQAd2UrlH21pD2sNJ8JrmDy0sxbpb0Laacy0pdc+A5CUAk59MEEpfi2ceKP2CqIVpNji1uQ79C5Q1iarPFshpRor5tumLw1AouZ936h56FgdwBA8mUAAkgNW09up6k2iiMZidIIKlRzPhMP/tnPbhKi75v1j5mSRC/grahA4syjembqxUekI+RF4BFiwq6N7hZnkZy2EGFXsOqGWdDgUIztTqh6dOueNUirzt6rBbRXLQCxyTOPJ2LNZuRhcABILmSz3KDHuuj6Ltr5cW79FeqVumSzYvjcZr8+34CDtdcBW7SbkTHk9gBI/wIKBQ6fe+3f4Q8yaNb2u0h7VyfGY6iz6pu5/Gv46HXfV1+1z/qRQVeGLu2yi3D1fcZvAH66GAMobzi1+vlt6c1cl+GGHdASbCoGriZDKby6iKywQR9GoUOEqRyX/wcXr1By1UOisCAZxwbl3jGo66kP0NUfwRpOi0HMl1PT1X5l/PBhrD7anK864eQ0inqwQzy6xyOQn6XA==
  template:
    metadata:
      creationTimestamp: null
      name: forge-api-secrets
      namespace: todde
    type: Opaque
