---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-postgres-credentials
  namespace: todde
spec:
  encryptedData:
    password: AgAQlcXF+xvvJKSgMTEqf7PnZYSEElHa40mScz2m0lhUTFLuiyQjxVi33TTYnw+sWxgquu7ReR5zbxxycazPQlSUpPW8MWkMbBY4/nj020dDK5AV25IZvnNjt5miP4++ISO/D8bqx6Cl44Tw335dAFMgD6fc4cXBcIx9plzpPeAbUl6mrM7QGxf7uAKkixCJx9ZyLhCboSgMFQ9ksjvNRR9byZKen0qCXHsxt8EdLJA1CvXyTQ26pgn58f9D9KUP0anpfoaL7Oq09q4ZzSFYDYFT/msi8noBOZTzYrXX8qe9mA8o9yflpBAxxnSU96ygvDkF6NCu2XZ4DumPf40OJJjfCgx393o6XRbxkBGzPGaQAlOHnVKt7h47JDZe7V/lxb49f+30gZazMwGs0nyPUtZN/POCjhDEQH1lXW47gA2LdgSYZiih1He+nXwKl8fnGsy/T//0VOMoUXahKh6ajAFMbfo8WcViQZ84kyp9gGQ31LDLLktDDprWMt2D8vZlksQhvQKoqiFflJ4Vmcw/u7Ti7mZH01ae5QY0cK/Ys7hzLppNjUgV7jhIPyTINP51thWjAPlIlpf/XtEhynJM1GFdljHVlgq5q0cS268/7wS+3HUxcila67req/cFdhN/xZdbgIcapMyVgPfbRgqwD5EZjInPIsLL3gk62Xtbl48hHwJCDZv8piXyP35n1rP1OpLsZjH+qP8QVrMKT2PbzSKx6kdqWO7b0IuhG/BSi2vFbg==
    username: AgBaZnCp9zS3Su/I2LBfOdamaaY75ATbYgsUEgJctIHPt4j34bcrVVGu0zl4OnVhLVyXqOiL4jgcoGe0+oSaqu8ydWOA5pGF2sVOm/HvalUZx39dcaUC+EgPsQog4BF+uAwggGoB2zgqgfY12FB8ShtTYuUEALKNB+2euzZsUmfLYxIeBLN0aJsus9ANr9EG4CYBlut+WS2z2zP6WYxDkt1Jzy31+O5zKKSems/hVRMkVHZ0MvqX1E3kL1DI7pfrT01OXf2uuDGjRA2xrGhcDV7teKpVyuKOgiiPX6yj6i9om74Y11Cqq6D67Pdsa/JC2GQvYrYIQ9i8eDYBDsyA+FDdKUd8jwEjM5It4Lt0aJw31BU2AqR/pKD5t+KJDNneZJHL5sn1JtvJ37q+THKYAfxJXmTW2MeS8evlH9nCZnr5wMGFLM4BG3z7/xnTx9xSsdNidXAYCiNpEN6VJl7yJfv+fDdboaxz5SErQd+XWWkWbe4OEq47lbLKUT+mvkp0/6b6lrVHKgkrVl8RWAAPh7JFdb9TEjsLw4Ehui6AjCv3EqpkHut4mPnBlvgXtKwR1GDbkT/2bBfvx4fi2Z/bGNBrRn/WUnGFDlLwBVB6SFm+VXuKsoIcX4Zo3zNtjXSlgg4ghHoft93/DVCcQpQCrnK/BinIsJPN2bCmClYO196sC9ye62XO8MZYPO/rdhLrh2TuwTooGw==
  template:
    metadata:
      creationTimestamp: null
      name: forge-postgres-credentials
      namespace: todde
    type: kubernetes.io/basic-auth
