apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-elasticsearch-exporter
    targetRevision: 6.4.0
    helm:
      valuesObject:
        es:
          uri: http://elastic:forge-elastic-secret-2026@forge-elasticsearch.todde.svc.cluster.local:9200
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true