apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-mongodb-exporter
    targetRevision: 3.6.0
    helm:
      valuesObject:
        image:
          repository: bitnami/mongodb-exporter
          tag: latest
        mongodb:
          uri: mongodb://forge-mongodb.todde.svc.cluster.local:27017/admin?directConnection=true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true