---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCewxgQ8tmidxlijDtX8zuLNAzkrTY2SYm937VQ6lnsmh+ZRGkPVjCwQMXfAwgyhqeeI5IG+dF4nCxZ9181PO+xdXLVnyoWUvOBS1Y8G8T7stiG0Gq7SKPAwkvm+2Z57KgRb8u/MyVuoHSyuxfGcfWizE/sCI0424WAmrW/buPVF+K6Vba4YI5OoL1EX4hDNX4vF1tIyk34JKZQTiwRgTlgTdfNhk9zump15JKkpseZBGz3vpUnJBxxTmUbpRt5bop5pz9AKQhJ4624oyBbY0fA9ACEylbWBTVB4LDd69c8f2Uf1do69+sUebHueZdjpBVjuRW1RrDNVkdQ4h6fJdzIFUfLvnShx6xtlR4o8H8+EO24YKX3R3KYn+6Kjow/br6ob2Bjsl06Rg23N/r8Xt3wrC/KPFBN383KWLoN8CvQXaaD8YhbXRDGQBBHSjAibltUUv65uNO1G5ENZrF5a2OhsMSfZ7oUy+prjWGYO2VI5axk8VpfgGLcFhps+gTNVaWze/tInJMwFSEEqmzlLAeLR1puTr87fRLEf5WFcqO+pjCZi+2FsEVoIe590iP/pSJqsGkDBKocGYQaAsF7wo0jI9zJ8TSxsuyoK4t0NRxzCadZdzlkw+yaaOEjRH0A2gc71xsH6EyqdS7wOFx04H/xYgdgjvvW92yaNldlk06odZxT7z8M/HMnx3Vkhz5jDEjpLaLaytF6fuv8GNOrhrgiPTjEIAvkNwoZVUEsO03facWjZHJf31nw/IZWhT9RTwI5kjEWdQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
