---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forge-api-secrets
  namespace: todde
spec:
  encryptedData:
    mongodb-uri: AgAos1RbUUr/jfJK2jrYIDebFxS6YqkGCy5NmTj5b5qM9Trnw4o8WZ31o+lCr8fBj9USAhtIQZ9wK/IBkzyvx3+SEc7YUf5iGFWO22vKkjoaNyW9bZ2/OtRA9C2I/fmpdUCdvrUKTNglMGi19C0l0vAP4iSHdvNJ/7NHP0kaxWTXu7wMfw64BAMLqnPK2Pq6/9ZIYhZJBQW40XKxX1x3U8fDbLuefXLUgbOagAkJG5JQ7A7hNXXzUQA302OxbCJxc8rsXpo3cw/wkr8//pSVLticxjsiIA1rvjwMQsGpmasxlksfGrx/SOPYRl2HHF6MfwfmCVhZ7lz7a7vxYljK1APGIPz+MiOnOv43hpzll0b+pN4GXVNFZzJbRIPtJka/4wM5xTmiwa++izEee6YmRxt55pzuquiBm8HElG6B9AW1VsQCe2vLoAl9PqpkD2EyRrnjoEFGpkWr+l1vSnSOwakb+GhLlSHV2GxEfD+aMu4m3Zt05HNrcM+AfJcY368+KmTvha/EsOccmqOKj1oy+73Q5YsH0KVwtI3nDpdjvTrZnV83zwUMlXFOZYJ/HLigCbasy3lXrBkOaTHw8Z+X1pnYzaoFfWTkodOljYyB1nGf5CLWWokDbp1RP7lGhCjXMFVfihvu2Bul23eohaP/RFjNQsmQIM9u03v9kj/0r8sNHJY9hbVJIdqBewPTbRS4TYhkGS1WaN9eT6z9pJXbo21fP+293qytG66eN7myS8bKqcJDfq81MKC5BZy8Cr5kP5yPDubl39YI6VKm5zAUpopjOwJvWO9vbvlseFuy3flcXUvPOpuU7Xq26QvNN4hzCHJ6gMtQxqufkw==
  template:
    metadata:
      creationTimestamp: null
      name: forge-api-secrets
      namespace: todde
    type: Opaque
