apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: monitoring
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40
          args:
            - --web.listen-address=:9216
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-exporter-credentials
                  key: mongodb-uri
          ports:
            - containerPort: 9216
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi