apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    mongodb-uri: AgBNCaTVIdnZefPDsi+RAa7RYBIL9DVFmOO050ciKSCYTD7pc8nVLiI/mw7HtcihBMt1VME1zs3g51PzFla0+K6VZTWDZ1SvH298y8ec40rt36VWQw3FsEOshZAz1Mu9KZsh7OqO0RnVbD9lqf3NZB+xAONxkhEGrtBjSazWsTemvixKh1J7xg1vp6h5OxaeU72dG5xvImsiIMhQ+M7HsEZO6a8yQc+n76OhGIy11852eal3fNu/hkfmY6Ir9f6m3iRAYrhcHgun2bEtVQOfAbnbPAX+igx0JcbbfVIgk1T9zWvstVUCLAt+Fjc23SCeQ2G+gZtd5uRWkp6/zEEFoSDKdtA5zL7LGwuuGomRZQWZIzvYTbqzsB7CUVbLh1QTiF2/pbaOPcCdM5VfNiI/K2e2mmQpOTYhu7+rwhnR+DrZ0nWS0Tia+yEnDolmF7U8LUgTASbO3uBILGw+ZNDsV8b6e9To7H4ow8MU0/M74CMWo+TWs8Rnpv0ZcctexmZSh1ibwTlZhjffOF8zHAzK4+pTtfoT1C5gaGFiVucJwzCgiaO3BYZY6f3AZR1w1KGSXZeRNlFvEpa2i+IV5mvJYzUAeyqfEHZZdBi0WVoF02f84IvbU4lwPz9/AQGFGxzbiVZMp6nPMvWXyC0Aexpv14SGoHi1SlNeRPxAtkjuuJBM+da7fsZFBoem2e/pUVyDtMW9VfzAkFGexRC2DRPM7fQ8ehywuDddhtZXcLeDS3ta+h7PgGyrmzVzj4PrXjGBHxYs6lle+AfUHek7EeiUzhpUPCXWoTLMqwK74qYlRRZIQrpB+RnHVdFar/NG3T6M0NgQddcD3zN9bSM=
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-exporter-credentials
      namespace: monitoring